stages:
  - deploy

deploy-ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" > ~/.ssh/ec2-private-key
    - chmod 600 ~/.ssh/ec2-private-key
    - ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP "
        cd /home/ec2-user/api &&
        git pull &&
        pip install -r requirements.txt &&
        sudo systemctl restart myapi
      "
